apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    url: https://{{ GLOBALS.influxdb_host }}:8086
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
    version: 1
