{%- set ES = salt['grains.get']('master') -%}
{%- set ES_USER = salt['pillar.get']('elasticsearch:auth:users:so_elastic_user:user', '') %}
{%- set ES_PASS = salt['pillar.get']('elasticsearch:auth:users:so_elastic_user:pass', '') %}

output.elasticsearch:
  enabled: true
  hosts: ["https://{{ ES }}:9200"]
  username: "{{ ES_USER }}"
  password: "{{ ES_PASS }}"
  ssl.certificate_authorities: ["/usr/share/filebeat/intraca.crt"]
