grafana:
  config:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    smtp:
      enabled: false
#      host: localhost:25
#      user: myuser
      # If the password contains # or ; you have to wrap it with triple quotes wrapped by single quotes. Ex '"""#password;"""'
#      password: mypassword
#      cert_file: /etc/grafana/config/files/smtp_cert_file.crt
#      key_file: /etc/grafana/config/files/smtp_key_file.key
#      skip_verify: false
      from_address: admin@grafana.localhost
      from_name: Grafana
#      ehlo_identity: dashboard.example.com
#    auth.ldap:
#      enabled: false
#      config_file: /etc/grafana/config/files/ldap.toml
#      allow_sign_up: true
#    enterprise:
#      license_path: /opt/so/conf/grafana/etc/files/license.jwt
  dashboards:
    standalone:
      templating:
        list:
          - servername
          - containers
          - manint
          - monint
          - cpucount
      panels:
        row_overview:
          gridPos:
            x: 0
            y: 0
            h: 1
            w: 24
        system_uptime:
          gridPos:
            x: 0
            y: 1
            h: 4
            w: 4
        load_average_5_minute_singlestat:
          gridPos:
            x: 4
            y: 1
            h: 4
            w: 4

        zeek_packet_loss_singlestat:
          gridPos:
            x: 8
            y: 1
            h: 4
            w: 4
        suricata_packet_loss_singlestat:
          gridPos:
            x: 12
            y: 1
            h: 4
            w: 4
        pcap_packet_loss_singlestat:
          gridPos:
            x: 16
            y: 1
            h: 4
            w: 4
        estimated_eps_singlestat:
          gridPos:
            x: 20
            y: 1
            h: 4
            w: 4

        io_wait_singlestat:
          gridPos:
            x: 0
            y: 5
            h: 4
            w: 4
        monitor_traffic_singlestat:
          gridPos:
            x: 4
            y: 5
            h: 4
            w: 4
        cpu_usage_guage:
          gridPos:
            x: 8
            y: 5
            h: 4
            w: 2
        ram_usage_guage:
          gridPos:
            x: 10
            y: 5
            h: 4
            w: 2
        swap_usage_guage:
          gridPos:
            x: 12
            y: 5
            h: 4
            w: 2
        rootfs_used_guage:
          gridPos:
            x: 14
            y: 5
            h: 4
            w: 2
        nsm_used_guage:
          gridPos:
            x: 16
            y: 5
            h: 4
            w: 2
        pcap_retention_singlestat:
          gridPos:
            x: 18
            y: 5
            h: 4
            w: 2

        row_docker_details:
          gridPos:
            x: 0
            y: 9
            h: 1
            w: 24
        cpu_docker_combined_current_graph:
          gridPos:
            x: 0
            y: 10
            h: 8
            w: 24
        cpu_docker_combined_trend_graph:
          gridPos:
            x: 0
            y: 18
            h: 8
            w: 24
        memory_used_docker_combined_current_graph:
          gridPos:
            x: 0
            y: 26
            h: 8
            w: 24
        memory_used_docker_combined_trend_graph:
          gridPos:
            x: 0
            y: 34
            h: 8
            w: 24
        network_usage_docker_combined_current_graph:
          gridPos:
            x: 0
            y: 42
            h: 8
            w: 24
        network_usage_docker_combined_trend_graph:
          gridPos:
            x: 0
            y: 50
            h: 8
            w: 24
